import '../models/user.dart';
import '../models/customer.dart';
import '../models/supplier.dart';
import '../models/product.dart';
import '../models/phone_item.dart';
import '../models/sale.dart';
import '../models/purchase.dart';
import '../models/repair_job.dart';
import '../models/payment_record.dart';
import '../models/expense.dart';
import '../models/stock_movement.dart';
import '../models/warranty.dart';
import '../models/audit_log.dart';
import '../models/business_settings.dart';

class SampleData {
  static final BusinessSettings settings = BusinessSettings();

  static final List<AppUser> users = [
    AppUser(
      id: 'USR-001',
      name: 'Muhammad Asim',
      username: 'asim',
      phone: '0300-1234567',
      role: UserRole.owner,
      createdAt: DateTime.now().subtract(const Duration(days: 180)),
    ),
    AppUser(
      id: 'USR-002',
      name: 'Tariq Mehmood',
      username: 'tariq',
      phone: '0321-9876543',
      role: UserRole.technician,
      createdAt: DateTime.now().subtract(const Duration(days: 150)),
    ),
    AppUser(
      id: 'USR-003',
      name: 'Bilal Khan',
      username: 'bilal',
      phone: '0333-5566778',
      role: UserRole.salesStaff,
      createdAt: DateTime.now().subtract(const Duration(days: 120)),
    ),
    AppUser(
      id: 'USR-004',
      name: 'Hamza Ali',
      username: 'hamza',
      phone: '0345-4433221',
      role: UserRole.cashier,
      createdAt: DateTime.now().subtract(const Duration(days: 90)),
    ),
  ];

  static final List<Customer> customers = [
    Customer(
      id: 'CUST-001',
      name: 'Dr. Salman Farooq',
      phone: '0321-4567891',
      alternatePhone: '0300-9871234',
      address: 'House #45-B, Sector J, DHA Phase 5, Lahore',
      email: 'salman.farooq@gmail.com',
      notes: 'VIP customer, prefers original Apple & Samsung parts',
      totalPurchases: 185000.0,
      totalRepairs: 2,
      totalPaid: 165000.0,
      totalDue: 20000.0,
      createdAt: DateTime.now().subtract(const Duration(days: 60)),
    ),
    Customer(
      id: 'CUST-002',
      name: 'Zeeshan Ahmed',
      phone: '0300-8451290',
      alternatePhone: '042-35841234',
      address: 'Flat 12, Block C, Model Town, Lahore',
      email: 'zeeshan.ahmed99@yahoo.com',
      notes: 'Frequent buyer for accessories',
      totalPurchases: 45000.0,
      totalRepairs: 1,
      totalPaid: 45000.0,
      totalDue: 0.0,
      createdAt: DateTime.now().subtract(const Duration(days: 45)),
    ),
    Customer(
      id: 'CUST-003',
      name: 'Usman Ghani',
      phone: '0333-9876543',
      address: 'Civic Centre, Johar Town, Lahore',
      notes: 'Corporate client for staff devices',
      totalPurchases: 135000.0,
      totalRepairs: 1,
      totalPaid: 110000.0,
      totalDue: 25000.0,
      createdAt: DateTime.now().subtract(const Duration(days: 30)),
    ),
    Customer(
      id: 'CUST-004',
      name: 'Fatima Bibi',
      phone: '0345-1122334',
      address: 'Main Market, Gulberg III, Lahore',
      notes: 'Regular repair lab visitor',
      totalPurchases: 18500.0,
      totalRepairs: 2,
      totalPaid: 18500.0,
      totalDue: 0.0,
      createdAt: DateTime.now().subtract(const Duration(days: 20)),
    ),
    Customer(
      id: 'CUST-005',
      name: 'Khurram Shahzad',
      phone: '0312-3344556',
      address: 'Shaukat Khanum Road, Faisal Town, Lahore',
      notes: 'Bought Samsung S23 Ultra',
      totalPurchases: 245000.0,
      totalRepairs: 0,
      totalPaid: 235000.0,
      totalDue: 10000.0,
      createdAt: DateTime.now().subtract(const Duration(days: 10)),
    ),
  ];

  static final List<Supplier> suppliers = [
    Supplier(
      id: 'SUP-001',
      name: 'Tariq Wholesale Mobiles',
      company: 'Lahore Mobile Wholesale Co.',
      phone: '0301-4455667',
      email: 'sales@lahoremobilewholesale.com',
      address: 'Shop 14-16, 2nd Floor, Hall Road, Lahore',
      notes: 'Primary supplier for Samsung, Xiaomi, and Vivo handsets',
      totalPurchases: 850000.0,
      paidAmount: 750000.0,
      dueAmount: 100000.0,
      createdAt: DateTime.now().subtract(const Duration(days: 90)),
    ),
    Supplier(
      id: 'SUP-002',
      name: 'Rashid Sheikh',
      company: 'Al-Rehman Accessories & Spares Karachi',
      phone: '0322-8877665',
      email: 'alrehman.accessories@gmail.com',
      address: 'Plaza 4, Saddar Electronic Market, Karachi',
      notes: 'Importer of original chargers, Anker power banks, and cables',
      totalPurchases: 320000.0,
      paidAmount: 280000.0,
      dueAmount: 40000.0,
      createdAt: DateTime.now().subtract(const Duration(days: 80)),
    ),
    Supplier(
      id: 'SUP-003',
      name: 'Imran LCD & Spares',
      company: 'Master Mobile Chip & LCD Hub',
      phone: '0334-1122998',
      email: 'masterlcds@gmail.com',
      address: 'Shop 88, Basement, Hafeez Centre, Lahore',
      notes: 'Supplier of OLED/AMOLED replacement screens, batteries & IC chips',
      totalPurchases: 260000.0,
      paidAmount: 260000.0,
      dueAmount: 0.0,
      createdAt: DateTime.now().subtract(const Duration(days: 75)),
    ),
  ];

  static final List<Product> products = [
    // Phones
    Product(
      id: 'PRD-001',
      name: 'Samsung Galaxy S23 Ultra',
      type: ProductType.phone,
      category: 'Smartphones',
      brand: 'Samsung',
      model: 'S23 Ultra 12/256GB',
      sku: 'SAM-S23U-256',
      barcode: '8806094771234',
      purchasePrice: 220000.0,
      salePrice: 245000.0,
      stockQuantity: 3,
      minStockAlert: 2,
      warrantyMonths: 12,
      description: 'Snapdragon 8 Gen 2, 200MP Camera, S-Pen included, Box Pack',
    ),
    Product(
      id: 'PRD-002',
      name: 'Apple iPhone 15 Pro Max',
      type: ProductType.phone,
      category: 'Smartphones',
      brand: 'Apple',
      model: '15 Pro Max 256GB',
      sku: 'APL-15PM-256',
      barcode: '195949012345',
      purchasePrice: 385000.0,
      salePrice: 415000.0,
      stockQuantity: 2,
      minStockAlert: 1,
      warrantyMonths: 12,
      description: 'Titanium chassis, A17 Pro Chip, 5x Telephoto zoom',
    ),
    Product(
      id: 'PRD-003',
      name: 'Apple iPhone 13 (Used/Mint)',
      type: ProductType.phone,
      category: 'Smartphones',
      brand: 'Apple',
      model: 'iPhone 13 128GB',
      sku: 'APL-13-128U',
      barcode: '194252701122',
      purchasePrice: 125000.0,
      salePrice: 139000.0,
      stockQuantity: 4,
      minStockAlert: 2,
      warrantyMonths: 1,
      description: 'Battery health 88%+, 10/10 condition with box',
    ),
    Product(
      id: 'PRD-004',
      name: 'Xiaomi Redmi Note 13',
      type: ProductType.phone,
      category: 'Smartphones',
      brand: 'Xiaomi',
      model: 'Note 13 8/256GB',
      sku: 'XMI-RN13-256',
      barcode: '6941812754321',
      purchasePrice: 46000.0,
      salePrice: 51500.0,
      stockQuantity: 8,
      minStockAlert: 3,
      warrantyMonths: 12,
      description: '108MP Camera, 120Hz AMOLED, 33W Fast charging',
    ),
    Product(
      id: 'PRD-005',
      name: 'Infinix Note 30',
      type: ProductType.phone,
      category: 'Smartphones',
      brand: 'Infinix',
      model: 'Note 30 8/256GB',
      sku: 'INF-N30-256',
      barcode: '4895180791234',
      purchasePrice: 38000.0,
      salePrice: 42500.0,
      stockQuantity: 6,
      minStockAlert: 3,
      warrantyMonths: 12,
      description: 'Helio G99 6nm, JBL Sound, 45W All-Round FastCharge',
    ),

    // Accessories
    Product(
      id: 'PRD-006',
      name: 'Samsung 25W Type-C Super Fast Charger',
      type: ProductType.accessory,
      category: 'Chargers',
      brand: 'Samsung',
      model: 'EP-TA800',
      sku: 'ACC-SAM-25W',
      barcode: '8806090123999',
      purchasePrice: 2200.0,
      salePrice: 3200.0,
      stockQuantity: 18,
      minStockAlert: 5,
      warrantyMonths: 6,
      description: 'Original adapter with PD 3.0 PPS protocol',
    ),
    Product(
      id: 'PRD-007',
      name: 'Apple 20W USB-C Power Adapter',
      type: ProductType.accessory,
      category: 'Chargers',
      brand: 'Apple',
      model: 'MHJE3ZM/A',
      sku: 'ACC-APL-20W',
      barcode: '194252157004',
      purchasePrice: 3400.0,
      salePrice: 4800.0,
      stockQuantity: 12,
      minStockAlert: 4,
      warrantyMonths: 6,
      description: 'Original Apple 20W Fast Charger with serial validation',
    ),
    Product(
      id: 'PRD-008',
      name: 'Anker 325 Power Bank 20000mAh',
      type: ProductType.accessory,
      category: 'Power Banks',
      brand: 'Anker',
      model: 'A1286',
      sku: 'ACC-ANK-20K',
      barcode: '194644023456',
      purchasePrice: 7200.0,
      salePrice: 9500.0,
      stockQuantity: 7,
      minStockAlert: 3,
      warrantyMonths: 18,
      description: 'PowerIQ technology, twin USB output, durable matte finish',
    ),
    Product(
      id: 'PRD-009',
      name: '9D Full Curved Glass Screen Protector',
      type: ProductType.accessory,
      category: 'Screen Protectors',
      brand: 'Premium Shield',
      model: 'Universal 9D',
      sku: 'ACC-GLS-9D',
      barcode: '789123456001',
      purchasePrice: 120.0,
      salePrice: 450.0,
      stockQuantity: 65,
      minStockAlert: 15,
      warrantyMonths: 0,
      description: 'Oleophobic coating, edge-to-edge explosion proof glass',
    ),
    Product(
      id: 'PRD-010',
      name: '65W Braided Fast Type-C Cable',
      type: ProductType.accessory,
      category: 'Cables',
      brand: 'Baseus',
      model: 'CATKLF-GG1',
      sku: 'ACC-CAB-65W',
      barcode: '6953156214567',
      purchasePrice: 650.0,
      salePrice: 1200.0,
      stockQuantity: 24,
      minStockAlert: 5,
      warrantyMonths: 3,
      description: 'High density nylon braided, 2-meter fast data & charging',
    ),
    Product(
      id: 'PRD-011',
      name: 'Original AKG Type-C Earphones',
      type: ProductType.accessory,
      category: 'Earphones',
      brand: 'Samsung',
      model: 'EO-IC100',
      sku: 'ACC-AKG-TC',
      barcode: '8806090287111',
      purchasePrice: 1600.0,
      salePrice: 2600.0,
      stockQuantity: 14,
      minStockAlert: 4,
      warrantyMonths: 3,
      description: 'Built-in DAC converter, braided cable, crystal clear mic',
    ),

    // Repair Parts
    Product(
      id: 'PRD-012',
      name: 'iPhone 11 Original OLED Display Assembly',
      type: ProductType.part,
      category: 'LCD / OLED Screens',
      brand: 'Apple Spare',
      model: 'iPhone 11',
      sku: 'PRT-APL-11LCD',
      barcode: '990100200301',
      purchasePrice: 7500.0,
      salePrice: 11500.0,
      stockQuantity: 4,
      minStockAlert: 2,
      warrantyMonths: 1,
      description: 'Original refurbished OLED panel with TrueTone EEPROM transfer support',
    ),
    Product(
      id: 'PRD-013',
      name: 'Samsung Galaxy A54 AMOLED Screen Assembly',
      type: ProductType.part,
      category: 'LCD / OLED Screens',
      brand: 'Samsung Spare',
      model: 'A54 5G',
      sku: 'PRT-SAM-A54LCD',
      barcode: '990100200302',
      purchasePrice: 9000.0,
      salePrice: 13500.0,
      stockQuantity: 3,
      minStockAlert: 2,
      warrantyMonths: 1,
      description: 'Original service pack 120Hz display with frame',
    ),
    Product(
      id: 'PRD-014',
      name: 'iPhone 13 High Capacity Replacement Battery',
      type: ProductType.part,
      category: 'Batteries',
      brand: 'Apple Spare',
      model: 'iPhone 13',
      sku: 'PRT-APL-13BAT',
      barcode: '990100200303',
      purchasePrice: 3800.0,
      salePrice: 5800.0,
      stockQuantity: 6,
      minStockAlert: 2,
      warrantyMonths: 3,
      description: '3227mAh original cell with IC spot-weld capability',
    ),
    Product(
      id: 'PRD-015',
      name: 'Samsung A54 Original Sub-Board Charging Port',
      type: ProductType.part,
      category: 'Charging Ports & Flex',
      brand: 'Samsung Spare',
      model: 'A54 5G',
      sku: 'PRT-SAM-A54CHG',
      barcode: '990100200304',
      purchasePrice: 1100.0,
      salePrice: 2000.0,
      stockQuantity: 5,
      minStockAlert: 2,
      warrantyMonths: 1,
      description: 'Original sub-board with microphone & fast charge IC',
    ),
    Product(
      id: 'PRD-016',
      name: 'Infinix Note 30 Display Screen OEM',
      type: ProductType.part,
      category: 'LCD / OLED Screens',
      brand: 'Infinix Spare',
      model: 'Note 30',
      sku: 'PRT-INF-N30LCD',
      barcode: '990100200305',
      purchasePrice: 3200.0,
      salePrice: 5000.0,
      stockQuantity: 1, // low stock test
      minStockAlert: 3,
      warrantyMonths: 1,
      description: 'High refresh rate IPS LCD replacement panel',
    ),
  ];

  static final List<PhoneItem> phoneItems = [
    PhoneItem(
      id: 'PHN-001',
      productId: 'PRD-001',
      brand: 'Samsung',
      model: 'Galaxy S23 Ultra',
      variant: '12GB / 256GB',
      ram: '12GB',
      storage: '256GB',
      color: 'Phantom Black',
      ptaStatus: 'PTA Approved',
      imei1: '358941092837461',
      imei2: '358941092837462',
      serialNumber: 'R5CW301X9AA',
      purchasePrice: 220000.0,
      salePrice: 245000.0,
      supplierId: 'SUP-001',
      supplierName: 'Lahore Mobile Wholesale Co.',
      purchaseDate: DateTime.now().subtract(const Duration(days: 15)),
      warrantyPeriod: '1 Year Official Samsung Pakistan',
      condition: 'New',
      status: 'In Stock',
      notes: 'Official box pack seal intact',
    ),
    PhoneItem(
      id: 'PHN-002',
      productId: 'PRD-001',
      brand: 'Samsung',
      model: 'Galaxy S23 Ultra',
      variant: '12GB / 256GB',
      ram: '12GB',
      storage: '256GB',
      color: 'Green',
      ptaStatus: 'PTA Approved',
      imei1: '358941092837463',
      imei2: '358941092837464',
      serialNumber: 'R5CW301X9AB',
      purchasePrice: 220000.0,
      salePrice: 245000.0,
      supplierId: 'SUP-001',
      supplierName: 'Lahore Mobile Wholesale Co.',
      purchaseDate: DateTime.now().subtract(const Duration(days: 14)),
      warrantyPeriod: '1 Year Official Samsung Pakistan',
      condition: 'New',
      status: 'In Stock',
    ),
    PhoneItem(
      id: 'PHN-003',
      productId: 'PRD-001',
      brand: 'Samsung',
      model: 'Galaxy S23 Ultra',
      variant: '12GB / 256GB',
      ram: '12GB',
      storage: '256GB',
      color: 'Cream',
      ptaStatus: 'PTA Approved',
      imei1: '358941092837465',
      imei2: '358941092837466',
      serialNumber: 'R5CW301X9AC',
      purchasePrice: 220000.0,
      salePrice: 245000.0,
      supplierId: 'SUP-001',
      supplierName: 'Lahore Mobile Wholesale Co.',
      customerId: 'CUST-005',
      customerName: 'Khurram Shahzad',
      purchaseDate: DateTime.now().subtract(const Duration(days: 20)),
      soldDate: DateTime.now().subtract(const Duration(days: 10)),
      saleInvoiceNumber: 'INV-1001',
      warrantyPeriod: '1 Year Official Samsung Pakistan',
      condition: 'New',
      status: 'Sold',
    ),
    PhoneItem(
      id: 'PHN-004',
      productId: 'PRD-002',
      brand: 'Apple',
      model: 'iPhone 15 Pro Max',
      variant: '256GB',
      ram: '8GB',
      storage: '256GB',
      color: 'Natural Titanium',
      ptaStatus: 'PTA Approved',
      imei1: '354892019284711',
      imei2: '354892019284712',
      serialNumber: 'G6TL901XP2',
      purchasePrice: 385000.0,
      salePrice: 415000.0,
      supplierId: 'SUP-001',
      supplierName: 'Lahore Mobile Wholesale Co.',
      purchaseDate: DateTime.now().subtract(const Duration(days: 8)),
      warrantyPeriod: '1 Year Apple Official',
      condition: 'New',
      status: 'In Stock',
      notes: 'Physical dual SIM variant',
    ),
    PhoneItem(
      id: 'PHN-005',
      productId: 'PRD-003',
      brand: 'Apple',
      model: 'iPhone 13',
      variant: '128GB',
      ram: '4GB',
      storage: '128GB',
      color: 'Midnight',
      ptaStatus: 'CPID Approved',
      imei1: '356781029384755',
      imei2: '356781029384756',
      serialNumber: 'FFKLP0912X',
      purchasePrice: 125000.0,
      salePrice: 139000.0,
      supplierId: 'SUP-001',
      supplierName: 'Lahore Mobile Wholesale Co.',
      customerId: 'CUST-003',
      customerName: 'Usman Ghani',
      purchaseDate: DateTime.now().subtract(const Duration(days: 35)),
      soldDate: DateTime.now().subtract(const Duration(days: 5)),
      saleInvoiceNumber: 'INV-1002',
      warrantyPeriod: '1 Month Shop Checking Warranty',
      condition: 'Used',
      status: 'Sold',
      notes: 'Mint condition, battery health 89%',
    ),
    PhoneItem(
      id: 'PHN-006',
      productId: 'PRD-004',
      brand: 'Xiaomi',
      model: 'Redmi Note 13',
      variant: '8GB / 256GB',
      ram: '8GB',
      storage: '256GB',
      color: 'Ocean Sunset',
      ptaStatus: 'PTA Approved',
      imei1: '869201928374619',
      imei2: '869201928374620',
      serialNumber: 'XM13N98012A',
      purchasePrice: 46000.0,
      salePrice: 51500.0,
      supplierId: 'SUP-001',
      supplierName: 'Lahore Mobile Wholesale Co.',
      purchaseDate: DateTime.now().subtract(const Duration(days: 12)),
      warrantyPeriod: '1 Year Airlink Official',
      condition: 'New',
      status: 'In Stock',
    ),
  ];

  static final List<RepairJob> repairJobs = [
    RepairJob(
      id: 'REP-UUID-001',
      jobId: 'REP-1001',
      customerId: 'CUST-001',
      customerName: 'Dr. Salman Farooq',
      customerPhone: '0321-4567891',
      customerAddress: 'DHA Phase 5, Lahore',
      deviceBrand: 'Apple',
      deviceModel: 'iPhone 11 (64GB)',
      imei: '359128374615243',
      color: 'Black',
      deviceCondition: 'Cracked front glass, minor frame scuffs',
      reportedProblem: 'Screen glass broken, touch working intermittently after drop',
      technicianNotes: 'Needs original OLED assembly replacement & TrueTone programming',
      accessoriesReceived: 'Device with original silicone case',
      lockPinOrPassword: '112233',
      estimatedCost: 13500.0,
      advancePaid: 5000.0,
      laborCharges: 2000.0,
      otherCharges: 0.0,
      discount: 500.0,
      finalTotal: 13000.0,
      remainingDue: 8000.0,
      paymentMethod: 'Cash',
      status: RepairStatus.inProgress,
      technicianId: 'USR-002',
      technicianName: 'Tariq Mehmood',
      expectedDeliveryDate: DateTime.now().add(const Duration(days: 1)),
      createdAt: DateTime.now().subtract(const Duration(days: 1, hours: 3)),
      partsUsed: [
        RepairPart(
          id: 'RP-001',
          productId: 'PRD-012',
          partName: 'iPhone 11 Original OLED Display Assembly',
          quantity: 1,
          costPrice: 7500.0,
          sellingPrice: 11500.0,
        ),
      ],
      history: [
        RepairStatusHistory(
          id: 'RSH-001',
          repairId: 'REP-UUID-001',
          status: RepairStatus.received,
          changedBy: 'Muhammad Asim',
          timestamp: DateTime.now().subtract(const Duration(days: 1, hours: 3)),
          notes: 'Device received, advance Rs. 5,000 paid via Cash',
        ),
        RepairStatusHistory(
          id: 'RSH-002',
          repairId: 'REP-UUID-001',
          status: RepairStatus.inspection,
          changedBy: 'Tariq Mehmood',
          timestamp: DateTime.now().subtract(const Duration(days: 1, hours: 1)),
          notes: 'Inspected: Motherboard and face ID safe, OLED replaced',
        ),
        RepairStatusHistory(
          id: 'RSH-003',
          repairId: 'REP-UUID-001',
          status: RepairStatus.inProgress,
          changedBy: 'Tariq Mehmood',
          timestamp: DateTime.now().subtract(const Duration(hours: 4)),
          notes: 'Assembly installed, TrueTone transfer in progress',
        ),
      ],
    ),
    RepairJob(
      id: 'REP-UUID-002',
      jobId: 'REP-1002',
      customerId: 'CUST-002',
      customerName: 'Zeeshan Ahmed',
      customerPhone: '0300-8451290',
      deviceBrand: 'Samsung',
      deviceModel: 'Galaxy A54 5G',
      imei: '357829104857291',
      color: 'Awesome Violet',
      deviceCondition: 'Mint condition, no cracks',
      reportedProblem: 'Phone not charging properly, slow charging and loose cable port',
      technicianNotes: 'Sub-board charging IC burnt, replaced with original module',
      accessoriesReceived: 'Phone Only',
      lockPinOrPassword: 'Pattern: L-Shape',
      estimatedCost: 3500.0,
      advancePaid: 1500.0,
      laborCharges: 1500.0,
      otherCharges: 0.0,
      discount: 0.0,
      finalTotal: 3500.0,
      remainingDue: 2000.0,
      paymentMethod: 'JazzCash',
      status: RepairStatus.readyForDelivery,
      technicianId: 'USR-002',
      technicianName: 'Tariq Mehmood',
      expectedDeliveryDate: DateTime.now(),
      createdAt: DateTime.now().subtract(const Duration(days: 2)),
      partsUsed: [
        RepairPart(
          id: 'RP-002',
          productId: 'PRD-015',
          partName: 'Samsung A54 Original Sub-Board Charging Port',
          quantity: 1,
          costPrice: 1100.0,
          sellingPrice: 2000.0,
        ),
      ],
      history: [
        RepairStatusHistory(
          id: 'RSH-004',
          repairId: 'REP-UUID-002',
          status: RepairStatus.received,
          changedBy: 'Bilal Khan',
          timestamp: DateTime.now().subtract(const Duration(days: 2)),
          notes: 'Job created, Advance Rs. 1,500 received via JazzCash',
        ),
        RepairStatusHistory(
          id: 'RSH-005',
          repairId: 'REP-UUID-002',
          status: RepairStatus.inProgress,
          changedBy: 'Tariq Mehmood',
          timestamp: DateTime.now().subtract(const Duration(days: 1)),
          notes: 'Charging port board replaced',
        ),
        RepairStatusHistory(
          id: 'RSH-006',
          repairId: 'REP-UUID-002',
          status: RepairStatus.completed,
          changedBy: 'Tariq Mehmood',
          timestamp: DateTime.now().subtract(const Duration(hours: 5)),
          notes: 'Fast charging tested up to 25W successfully',
        ),
        RepairStatusHistory(
          id: 'RSH-007',
          repairId: 'REP-UUID-002',
          status: RepairStatus.readyForDelivery,
          changedBy: 'Tariq Mehmood',
          timestamp: DateTime.now().subtract(const Duration(hours: 3)),
          notes: 'Customer notified via WhatsApp/SMS to collect device',
        ),
      ],
    ),
    RepairJob(
      id: 'REP-UUID-003',
      jobId: 'REP-1003',
      customerId: 'CUST-003',
      customerName: 'Usman Ghani',
      customerPhone: '0333-9876543',
      deviceBrand: 'Apple',
      deviceModel: 'iPhone 13',
      imei: '359920194857211',
      color: 'Blue',
      deviceCondition: 'Water exposure reported',
      reportedProblem: 'Phone dropped in water, black screen, vibrating on charging',
      technicianNotes: 'Motherboard short circuit test underway, sonic cleaning needed',
      accessoriesReceived: 'Device + Box',
      lockPinOrPassword: '7860',
      estimatedCost: 15000.0,
      advancePaid: 3000.0,
      laborCharges: 3500.0,
      otherCharges: 500.0,
      discount: 0.0,
      finalTotal: 15000.0,
      remainingDue: 12000.0,
      paymentMethod: 'Cash',
      status: RepairStatus.inspection,
      technicianId: 'USR-002',
      technicianName: 'Tariq Mehmood',
      expectedDeliveryDate: DateTime.now().add(const Duration(days: 3)),
      createdAt: DateTime.now().subtract(const Duration(hours: 6)),
      history: [
        RepairStatusHistory(
          id: 'RSH-008',
          repairId: 'REP-UUID-003',
          status: RepairStatus.received,
          changedBy: 'Muhammad Asim',
          timestamp: DateTime.now().subtract(const Duration(hours: 6)),
          notes: 'Water damaged device received with disclaimer signed',
        ),
        RepairStatusHistory(
          id: 'RSH-009',
          repairId: 'REP-UUID-003',
          status: RepairStatus.inspection,
          changedBy: 'Tariq Mehmood',
          timestamp: DateTime.now().subtract(const Duration(hours: 4)),
          notes: 'Disassembled and board placed in ultrasonic cleaner',
        ),
      ],
    ),
    RepairJob(
      id: 'REP-UUID-004',
      jobId: 'REP-1004',
      customerId: 'CUST-004',
      customerName: 'Fatima Bibi',
      customerPhone: '0345-1122334',
      deviceBrand: 'Xiaomi',
      deviceModel: 'Redmi Note 12',
      imei: '861928374615290',
      color: 'Ice Blue',
      deviceCondition: 'Good, dust in speaker mesh',
      reportedProblem: 'No sound from ear speaker during voice calls',
      technicianNotes: 'Cleaned ear speaker mesh and replaced damaged flex',
      accessoriesReceived: 'Phone Only',
      lockPinOrPassword: '0000',
      estimatedCost: 1800.0,
      advancePaid: 1800.0,
      laborCharges: 1200.0,
      otherCharges: 0.0,
      discount: 200.0,
      finalTotal: 1800.0,
      remainingDue: 0.0,
      paymentMethod: 'Cash',
      status: RepairStatus.delivered,
      technicianId: 'USR-002',
      technicianName: 'Tariq Mehmood',
      expectedDeliveryDate: DateTime.now().subtract(const Duration(days: 3)),
      createdAt: DateTime.now().subtract(const Duration(days: 4)),
      deliveredAt: DateTime.now().subtract(const Duration(days: 3)),
      partsUsed: [
        RepairPart(
          id: 'RP-003',
          productId: 'PRD-010',
          partName: 'Ear Speaker Transducer',
          quantity: 1,
          costPrice: 300.0,
          sellingPrice: 800.0,
        ),
      ],
      history: [
        RepairStatusHistory(
          id: 'RSH-010',
          repairId: 'REP-UUID-004',
          status: RepairStatus.received,
          changedBy: 'Bilal Khan',
          timestamp: DateTime.now().subtract(const Duration(days: 4)),
          notes: 'Full payment received up-front',
        ),
        RepairStatusHistory(
          id: 'RSH-011',
          repairId: 'REP-UUID-004',
          status: RepairStatus.completed,
          changedBy: 'Tariq Mehmood',
          timestamp: DateTime.now().subtract(const Duration(days: 3, hours: 5)),
          notes: 'Speaker replaced and tested loud and clear',
        ),
        RepairStatusHistory(
          id: 'RSH-012',
          repairId: 'REP-UUID-004',
          status: RepairStatus.delivered,
          changedBy: 'Bilal Khan',
          timestamp: DateTime.now().subtract(const Duration(days: 3)),
          notes: 'Customer collected device, signed delivery slip',
        ),
      ],
    ),
  ];

  static final List<Sale> sales = [
    Sale(
      id: 'SAL-001',
      invoiceNumber: 'INV-1001',
      customerId: 'CUST-005',
      customerName: 'Khurram Shahzad',
      customerPhone: '0312-3344556',
      saleDate: DateTime.now().subtract(const Duration(days: 10)),
      subtotal: 248200.0,
      discount: 3200.0,
      tax: 0.0,
      grandTotal: 245000.0,
      paidAmount: 235000.0,
      dueAmount: 10000.0,
      paymentMethod: 'Split',
      paymentBreakdown: {
        'Cash': 150000.0,
        'Bank Transfer': 85000.0,
        'Due': 10000.0,
      },
      cashierId: 'USR-001',
      cashierName: 'Muhammad Asim',
      status: 'Completed',
      notes: 'Customer promised to pay remaining Rs. 10,000 next Monday',
      items: [
        SaleItem(
          id: 'SI-001',
          productId: 'PRD-001',
          productName: 'Samsung Galaxy S23 Ultra (Cream)',
          productType: 'phone',
          imei: '358941092837465',
          quantity: 1,
          unitPrice: 245000.0,
          costPrice: 220000.0,
          discount: 0.0,
          total: 245000.0,
          warrantyMonths: 12,
        ),
        SaleItem(
          id: 'SI-002',
          productId: 'PRD-006',
          productName: 'Samsung 25W Type-C Super Fast Charger',
          productType: 'accessory',
          quantity: 1,
          unitPrice: 3200.0,
          costPrice: 2200.0,
          discount: 3200.0, // bundled free
          total: 0.0,
          warrantyMonths: 6,
        ),
      ],
    ),
    Sale(
      id: 'SAL-002',
      invoiceNumber: 'INV-1002',
      customerId: 'CUST-003',
      customerName: 'Usman Ghani',
      customerPhone: '0333-9876543',
      saleDate: DateTime.now().subtract(const Duration(days: 5)),
      subtotal: 148500.0,
      discount: 1500.0,
      tax: 0.0,
      grandTotal: 147000.0,
      paidAmount: 122000.0,
      dueAmount: 25000.0,
      paymentMethod: 'Split',
      paymentBreakdown: {
        'JazzCash': 100000.0,
        'Cash': 22000.0,
        'Due': 25000.0,
      },
      cashierId: 'USR-003',
      cashierName: 'Bilal Khan',
      status: 'Completed',
      notes: 'iPhone 13 used phone sale + Original Anker Power Bank',
      items: [
        SaleItem(
          id: 'SI-003',
          productId: 'PRD-003',
          productName: 'Apple iPhone 13 (Used/Mint)',
          productType: 'phone',
          imei: '356781029384755',
          quantity: 1,
          unitPrice: 139000.0,
          costPrice: 125000.0,
          discount: 1000.0,
          total: 138000.0,
          warrantyMonths: 1,
        ),
        SaleItem(
          id: 'SI-004',
          productId: 'PRD-008',
          productName: 'Anker 325 Power Bank 20000mAh',
          productType: 'accessory',
          quantity: 1,
          unitPrice: 9500.0,
          costPrice: 7200.0,
          discount: 500.0,
          total: 9000.0,
          warrantyMonths: 18,
        ),
      ],
    ),
    Sale(
      id: 'SAL-003',
      invoiceNumber: 'INV-1003',
      customerId: 'CUST-002',
      customerName: 'Zeeshan Ahmed',
      customerPhone: '0300-8451290',
      saleDate: DateTime.now().subtract(const Duration(days: 1)),
      subtotal: 5850.0,
      discount: 350.0,
      tax: 0.0,
      grandTotal: 5500.0,
      paidAmount: 5500.0,
      dueAmount: 0.0,
      paymentMethod: 'Cash',
      paymentBreakdown: {'Cash': 5500.0},
      cashierId: 'USR-004',
      cashierName: 'Hamza Ali',
      status: 'Completed',
      notes: 'Accessories sale',
      items: [
        SaleItem(
          id: 'SI-005',
          productId: 'PRD-007',
          productName: 'Apple 20W USB-C Power Adapter',
          productType: 'accessory',
          quantity: 1,
          unitPrice: 4800.0,
          costPrice: 3400.0,
          discount: 200.0,
          total: 4600.0,
          warrantyMonths: 6,
        ),
        SaleItem(
          id: 'SI-006',
          productId: 'PRD-009',
          productName: '9D Full Curved Glass Screen Protector',
          productType: 'accessory',
          quantity: 2,
          unitPrice: 450.0,
          costPrice: 120.0,
          discount: 0.0,
          total: 900.0,
          warrantyMonths: 0,
        ),
      ],
    ),
  ];

  static final List<Purchase> purchases = [
    Purchase(
      id: 'PUR-001',
      invoiceNumber: 'PUR-8821',
      supplierId: 'SUP-001',
      supplierName: 'Lahore Mobile Wholesale Co.',
      purchaseDate: DateTime.now().subtract(const Duration(days: 15)),
      totalAmount: 660000.0,
      discount: 10000.0,
      paidAmount: 550000.0,
      dueAmount: 100000.0,
      paymentMethod: 'Bank Transfer',
      status: 'Received',
      notes: 'Purchased 3 units Samsung S23 Ultra',
      items: [
        PurchaseItem(
          id: 'PI-001',
          productId: 'PRD-001',
          productName: 'Samsung Galaxy S23 Ultra',
          productType: 'phone',
          quantity: 3,
          purchasePrice: 220000.0,
          total: 660000.0,
          imeiList: [
            '358941092837461',
            '358941092837463',
            '358941092837465',
          ],
        ),
      ],
    ),
    Purchase(
      id: 'PUR-002',
      invoiceNumber: 'PUR-9410',
      supplierId: 'SUP-002',
      supplierName: 'Al-Rehman Accessories Karachi',
      purchaseDate: DateTime.now().subtract(const Duration(days: 10)),
      totalAmount: 145000.0,
      discount: 5000.0,
      paidAmount: 100000.0,
      dueAmount: 40000.0,
      paymentMethod: 'Online Transfer',
      status: 'Received',
      notes: 'Restocked chargers and Anker power banks',
      items: [
        PurchaseItem(
          id: 'PI-002',
          productId: 'PRD-006',
          productName: 'Samsung 25W Type-C Super Fast Charger',
          productType: 'accessory',
          quantity: 20,
          purchasePrice: 2200.0,
          total: 44000.0,
        ),
        PurchaseItem(
          id: 'PI-003',
          productId: 'PRD-008',
          productName: 'Anker 325 Power Bank 20000mAh',
          productType: 'accessory',
          quantity: 10,
          purchasePrice: 7200.0,
          total: 72000.0,
        ),
        PurchaseItem(
          id: 'PI-004',
          productId: 'PRD-007',
          productName: 'Apple 20W USB-C Power Adapter',
          productType: 'accessory',
          quantity: 8,
          purchasePrice: 3400.0,
          total: 27200.0,
        ),
      ],
    ),
  ];

  static final List<PaymentRecord> paymentRecords = [
    PaymentRecord(
      id: 'PAY-001',
      receiptNumber: 'REC-1001',
      type: 'customer_due_payment',
      referenceId: 'INV-1001',
      entityId: 'CUST-005',
      entityName: 'Khurram Shahzad',
      amount: 15000.0,
      paymentMethod: 'JazzCash',
      paymentDate: DateTime.now().subtract(const Duration(days: 3)),
      notes: 'Received partial due payment for S23 Ultra',
      collectedBy: 'Hamza Ali',
    ),
    PaymentRecord(
      id: 'PAY-002',
      receiptNumber: 'REC-1002',
      type: 'supplier_due_payment',
      referenceId: 'PUR-8821',
      entityId: 'SUP-001',
      entityName: 'Lahore Mobile Wholesale Co.',
      amount: 50000.0,
      paymentMethod: 'Bank Transfer',
      paymentDate: DateTime.now().subtract(const Duration(days: 2)),
      notes: 'Paid part of wholesale handset consignment',
      collectedBy: 'Muhammad Asim',
    ),
    PaymentRecord(
      id: 'PAY-003',
      receiptNumber: 'REC-1003',
      type: 'repair_advance',
      referenceId: 'REP-1001',
      entityId: 'CUST-001',
      entityName: 'Dr. Salman Farooq',
      amount: 5000.0,
      paymentMethod: 'Cash',
      paymentDate: DateTime.now().subtract(const Duration(days: 1)),
      notes: 'Advance deposit for iPhone 11 screen replacement',
      collectedBy: 'Muhammad Asim',
    ),
  ];

  static final List<Expense> expenses = [
    Expense(
      id: 'EXP-001',
      title: 'Shop Rent - Hafeez Centre (1st Floor)',
      category: 'Rent',
      amount: 65000.0,
      date: DateTime.now().subtract(const Duration(days: 5)),
      paymentMethod: 'Bank Transfer',
      notes: 'Shop #42 monthly rent paid to plaza management',
      recordedBy: 'Muhammad Asim',
    ),
    Expense(
      id: 'EXP-002',
      title: 'LESCO Electricity Bill',
      category: 'Electricity',
      amount: 28500.0,
      date: DateTime.now().subtract(const Duration(days: 7)),
      paymentMethod: 'JazzCash',
      notes: 'Paid via JazzCash Bill Payment portal',
      recordedBy: 'Muhammad Asim',
    ),
    Expense(
      id: 'EXP-003',
      title: 'PTCL Flash Fiber Internet 50Mbps',
      category: 'Internet',
      amount: 4200.0,
      date: DateTime.now().subtract(const Duration(days: 9)),
      paymentMethod: 'Easypaisa',
      notes: 'High speed connection for lab firmware flashing & iCloud unlocks',
      recordedBy: 'Hamza Ali',
    ),
    Expense(
      id: 'EXP-004',
      title: 'Technician Weekly Advance (Tariq)',
      category: 'Salaries',
      amount: 15000.0,
      date: DateTime.now().subtract(const Duration(days: 4)),
      paymentMethod: 'Cash',
      notes: 'Weekly commission & salary advance',
      recordedBy: 'Muhammad Asim',
    ),
    Expense(
      id: 'EXP-005',
      title: 'Daily Tea, Mineral Water & Refreshments',
      category: 'Tea & Refreshments',
      amount: 1850.0,
      date: DateTime.now().subtract(const Duration(days: 1)),
      paymentMethod: 'Cash',
      notes: 'Tea from plaza cafe for customers and technicians',
      recordedBy: 'Bilal Khan',
    ),
    Expense(
      id: 'EXP-006',
      title: 'Microscope Lens & Soldering Wire',
      category: 'Repair Tools',
      amount: 6200.0,
      date: DateTime.now().subtract(const Duration(days: 12)),
      paymentMethod: 'Cash',
      notes: 'Mechanic 0.01mm jumper wire and flux paste',
      recordedBy: 'Tariq Mehmood',
    ),
  ];

  static final List<StockMovement> stockMovements = [
    StockMovement(
      id: 'SM-001',
      productId: 'PRD-001',
      productName: 'Samsung Galaxy S23 Ultra',
      imei: '358941092837465',
      movementType: 'purchase',
      quantity: 3,
      previousStock: 0,
      newStock: 3,
      referenceId: 'PUR-8821',
      date: DateTime.now().subtract(const Duration(days: 15)),
      reason: 'Consignment arrival from Lahore Wholesale',
      performedBy: 'Muhammad Asim',
    ),
    StockMovement(
      id: 'SM-002',
      productId: 'PRD-001',
      productName: 'Samsung Galaxy S23 Ultra',
      imei: '358941092837465',
      movementType: 'sale',
      quantity: 1,
      previousStock: 3,
      newStock: 2,
      referenceId: 'INV-1001',
      date: DateTime.now().subtract(const Duration(days: 10)),
      reason: 'Sold to Khurram Shahzad',
      performedBy: 'Muhammad Asim',
    ),
    StockMovement(
      id: 'SM-003',
      productId: 'PRD-012',
      productName: 'iPhone 11 Original OLED Display Assembly',
      movementType: 'repair_use',
      quantity: 1,
      previousStock: 5,
      newStock: 4,
      referenceId: 'REP-1001',
      date: DateTime.now().subtract(const Duration(days: 1)),
      reason: 'Consumed in repair job for Dr. Salman Farooq',
      performedBy: 'Tariq Mehmood',
    ),
    StockMovement(
      id: 'SM-004',
      productId: 'PRD-009',
      productName: '9D Full Curved Glass Screen Protector',
      movementType: 'damaged',
      quantity: 2,
      previousStock: 67,
      newStock: 65,
      referenceId: 'ADJ-001',
      date: DateTime.now().subtract(const Duration(days: 6)),
      reason: 'Cracked during unpacking transit',
      performedBy: 'Bilal Khan',
    ),
  ];

  static final List<WarrantyRecord> warranties = [
    WarrantyRecord(
      id: 'WAR-001',
      type: 'phone',
      referenceId: 'INV-1001',
      customerId: 'CUST-005',
      customerName: 'Khurram Shahzad',
      customerPhone: '0312-3344556',
      itemName: 'Samsung Galaxy S23 Ultra (Phantom Black)',
      imei: '358941092837465',
      startDate: DateTime.now().subtract(const Duration(days: 10)),
      endDate: DateTime.now().add(const Duration(days: 355)),
      warrantyTerms: '1 Year Official Samsung Pakistan Warranty with original box & card',
      status: 'Active',
    ),
    WarrantyRecord(
      id: 'WAR-002',
      type: 'phone',
      referenceId: 'INV-1002',
      customerId: 'CUST-003',
      customerName: 'Usman Ghani',
      customerPhone: '0333-9876543',
      itemName: 'Apple iPhone 13 128GB Midnight (Used)',
      imei: '356781029384755',
      startDate: DateTime.now().subtract(const Duration(days: 5)),
      endDate: DateTime.now().add(const Duration(days: 25)),
      warrantyTerms: '1 Month Shop Checking Warranty (Display & water damage excluded)',
      status: 'Active',
    ),
    WarrantyRecord(
      id: 'WAR-003',
      type: 'repair',
      referenceId: 'REP-1004',
      customerId: 'CUST-004',
      customerName: 'Fatima Bibi',
      customerPhone: '0345-1122334',
      itemName: 'Xiaomi Redmi Note 12 Ear Speaker Repair',
      imei: '861928374615290',
      startDate: DateTime.now().subtract(const Duration(days: 3)),
      endDate: DateTime.now().add(const Duration(days: 12)),
      warrantyTerms: '15 Days Lab Service Warranty on replacement speaker',
      status: 'Active',
    ),
  ];

  static final List<AuditLog> auditLogs = [
    AuditLog(
      id: 'AUD-001',
      userId: 'USR-001',
      userName: 'Muhammad Asim',
      action: 'Sale Created',
      module: 'Sales / POS',
      recordId: 'INV-1001',
      details: 'Created sale for Khurram Shahzad. Total: Rs. 245,000, Advance: Rs. 235,000, Due: Rs. 10,000',
      timestamp: DateTime.now().subtract(const Duration(days: 10)),
    ),
    AuditLog(
      id: 'AUD-002',
      userId: 'USR-002',
      userName: 'Tariq Mehmood',
      action: 'Status Updated',
      module: 'Repair Lab',
      recordId: 'REP-1001',
      details: 'Updated status of Job REP-1001 from Inspection to In Progress. Added iPhone 11 OLED display part',
      timestamp: DateTime.now().subtract(const Duration(hours: 4)),
    ),
    AuditLog(
      id: 'AUD-003',
      userId: 'USR-001',
      userName: 'Muhammad Asim',
      action: 'Payment Received',
      module: 'Customer Dues',
      recordId: 'REC-1001',
      details: 'Received Rs. 15,000 from Khurram Shahzad via JazzCash against Invoice #INV-1001',
      timestamp: DateTime.now().subtract(const Duration(days: 3)),
    ),
  ];
}
